# See https://github.com/itadventurer/kafka-toolbox-pod/
apiVersion: v1
kind: Pod
metadata:
  name: kafka-toolbox
spec:
  containers:
    - name: kafka-toolbox
      image: itadventurer/kafka-toolbox:kafka-2.3.0
      env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-kafka-bootstrap:9092"
      command:
        - sleep
        - infinity
