global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'kafka'
    scrape_interval: 10s
    target_groups:
      - targets: [
        'kafka-1-jmx-exporter:80',
        'kafka-2-jmx-exporter:80',
        'kafka-3-jmx-exporter:80',]
